name: Build and Release Mods

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 🔍 Шаг 1: Проверяем код из репозитория
      - name: 🔍 Шаг 1. Клонирование репозитория
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      # 🔍 Шаг 2: Устанавливаем Python 2.7
      - name: 🔍 Шаг 2. Установка Python 2.7
        uses: actions/setup-python@v5
        with:
          python-version: "2.7"

      # 🔍 Шаг 3: Устанавливаем зависимости Python
      - name: 🔍 Шаг 3. Установка зависимостей
        shell: pwsh
        run: |
          Write-Host "🚀 [DEBUG] Installing required Python dependencies..."
          python -m pip install --upgrade pip setuptools wheel
          Write-Host "✅ [DEBUG] Dependencies installed successfully."

      # 🔍 Шаг 4: Обрабатываем версии модов
      - name: 🔍 Шаг 4. Обработка версии модов
        id: process_game_version
        shell: pwsh
        run: |
          Write-Host "🚀 [DEBUG] Processing mod versions..."
          $lesta_version="1.23.4.5"
          $wg_version="2.34.5.6"
          $mod_list="mod1;mod2;mod3"
          echo "lesta_version=$lesta_version" >> $env:GITHUB_ENV
          echo "wg_version=$wg_version" >> $env:GITHUB_ENV
          echo "mod_list=$mod_list" >> $env:GITHUB_ENV
          Write-Host "✅ [DEBUG] Versions processed: Lesta=$lesta_version, WG=$wg_version, Mods=($mod_list)"

      # 🔍 Шаг 5: Запускаем сборку модов
      - name: 🔍 Шаг 5. Запуск createRelease.py
        shell: pwsh
        run: |
          Write-Host "🚀 [DEBUG] Running createRelease.py..."
          & python .github/createRelease.py ${{ env.lesta_version }} ${{ env.wg_version }} ${{ env.mod_list }}
          Write-Host "✅ [DEBUG] createRelease.py execution finished."

      # 🔍 Шаг 6: Сохраняем артефакты сборки
      - name: 🔍 Шаг 6. Сохранение собранных архивов модов
        uses: actions/upload-artifact@v4
        with:
          name: built-mods
          path: "**/zip/*.zip"

      # 🔍 Шаг 7: Загружаем артефакты перед публикацией
      - name: 🔍 Шаг 7. Загрузка собранных архивов перед публикацией
        uses: actions/download-artifact@v4
        with:
          name: built-mods
          path: .

      # 🔍 Шаг 8: Разархивация built-mods.zip
      - name: 🔍 Шаг 8. Разархивация built-mods.zip перед публикацией
        shell: pwsh
        run: |
          Write-Host "🔍 [DEBUG] Checking for built-mods.zip..."
          if (-Not (Test-Path "built-mods.zip")) {
              Write-Host "❌ built-mods.zip not found! Skipping extraction."
              exit 1
          }

          Write-Host "🔍 [DEBUG] Extracting built-mods.zip..."
          Expand-Archive -Path built-mods.zip -DestinationPath . -Force
          Write-Host "✅ [DEBUG] Extraction complete."
          Get-ChildItem -Path . -Recurse | ForEach-Object { Write-Host "🔍 [DEBUG] Extracted file: $_" }

      # 🔍 Шаг 9: Проверка содержимого после разархивации
      - name: 🔍 Шаг 9. Проверка содержимого после разархивации
        shell: pwsh
        run: |
          Write-Host "🔍 [DEBUG] Listing extracted release files:"
          Get-ChildItem -Path . -Recurse -Filter "*.zip" | ForEach-Object { Write-Host "🔍 [DEBUG] Found archive: $_" }

      # 🚀 Шаг 10: Публикация релизов
      - name: 🚀 Шаг 10. Публикация релизов
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Write-Host "🚀 [DEBUG] Starting release publishing process..."
          $mod_list="${{ env.mod_list }}" -split ";"

          foreach ($mod in $mod_list) {
              Write-Host "🔍 [DEBUG] Processing mod: $mod"

              $wgArchivePath = "$mod/zip/${mod}_${{ env.wg_version }}.zip"
              $lestaArchivePath = "$mod/zip/${mod}_${{ env.lesta_version }}_RU.zip"

              Write-Host "🔍 [DEBUG] Checking WG archive path: $wgArchivePath"
              Write-Host "🔍 [DEBUG] Checking Lesta archive path: $lestaArchivePath"

              if (-not (Test-Path $wgArchivePath)) {
                  Write-Host "❌ WG archive not found for mod: $mod. Skipping."
                  continue
              }
              if (-not (Test-Path $lestaArchivePath)) {
                  Write-Host "❌ Lesta archive not found for mod: $mod. Skipping."
                  continue
              }

              try {
                  Write-Host "🚀 [DEBUG] Publishing release for mod: $mod"
                  gh release create "v1.0.0" "$wgArchivePath" "$lestaArchivePath" --title "Release $mod"
                  Write-Host "✅ Successfully published release for mod: $mod"
              } catch {
                  Write-Host "❌ Failed to publish release for mod: $mod. Error: $_"
              }
          }

      # 🛠️ Шаг 11: Итоговое тестирование после публикации
      - name: 🛠️ Шаг 11. Итоговое тестирование после публикации
        shell: pwsh
        run: |
          Write-Host "🔍 [DEBUG-TEST] Checking extracted .zip files after release:"
          Get-ChildItem -Path . -Recurse -Filter "*.zip" | ForEach-Object { Write-Host "🔍 [DEBUG-TEST] Archive found: $_" }

          Write-Host "🔍 [DEBUG-TEST] Checking for failed release logs:"
          Get-Content -Path "job-logs.txt" -Tail 50 | ForEach-Object { Write-Host "🔍 [DEBUG-TEST] $_" }

          Write-Host "🔍 [DEBUG-TEST] Checking if all mods were processed correctly..."
          foreach ($mod in $mod_list) {
              $wgArchivePath = "$mod/zip/${mod}_${{ env.wg_version }}.zip"
              $lestaArchivePath = "$mod/zip/${mod}_${{ env.lesta_version }}_RU.zip"

              if (Test-Path $wgArchivePath) {
                  Write-Host "✅ [DEBUG-TEST] Found WG archive for mod: $mod"
              } else {
                  Write-Host "❌ [DEBUG-TEST] MISSING WG archive for mod: $mod"
              }

              if (Test-Path $lestaArchivePath) {
                  Write-Host "✅ [DEBUG-TEST] Found Lesta archive for mod: $mod"
              } else {
                  Write-Host "❌ [DEBUG-TEST] MISSING Lesta archive for mod: $mod"
              }
          }
