name: Build and Release

on:
  push:
    branches:
      - master  # ветка, на которую пушить изменения

jobs:
  build:
    runs-on: windows-latest  # Используем Windows для сборки

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Получаем всю историю коммитов

    - name: Install Python 2.7 manually
      run: |
        $pythonUrl = "https://www.python.org/ftp/python/2.7.18/python-2.7.18.amd64.msi"
        $pythonInstaller = "$env:RUNNER_TEMP\python-2.7.18.amd64.msi"
        Invoke-WebRequest -Uri $pythonUrl -OutFile $pythonInstaller
        Start-Process msiexec.exe -ArgumentList "/i $pythonInstaller /quiet" -Wait
        $pythonPath = "C:\Python27"
        $pythonScriptsPath = "$pythonPath\Scripts"
        echo "$env:GITHUB_PATH += `"$pythonPath`";$pythonScriptsPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify Python installation
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Check commit message for release keywords
      id: check_commit
      run: |
        $commitMessage = git log -1 --pretty=%B
        $commitMessage = $commitMessage -replace '"', '`"'
        $releasePattern = "(?i)release|релиз"
        $allPattern = "(?i)all|всех|все|всё"
        $isRelease = $commitMessage -match $releasePattern
        $isAll = $commitMessage -match $allPattern

        if ($isRelease) {
          echo "DEBUG: Commit message contains release keyword."
          echo "DEBUG: commit_message=$commitMessage"
          echo "DEBUG: is_release=true"
          echo "commit_message=$commitMessage" >> $env:GITHUB_OUTPUT
          echo "is_release=true" >> $env:GITHUB_OUTPUT
          if ($isAll) {
            echo "DEBUG: is_all=true"
            echo "is_all=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "DEBUG: is_all=false"
            echo "is_all=false" >> $env:GITHUB_OUTPUT
          }
        } else {
          echo "DEBUG: Commit message does not contain release keyword. Skipping build."
          echo "DEBUG: is_release=false"
          echo "is_release=false" >> $env:GITHUB_OUTPUT
          echo "DEBUG: is_all=false"
          echo "is_all=false" >> $env:GITHUB_OUTPUT
        }

    - name: Pause to ensure environment variable is set 1
      run: sleep 10

    - name: Debug modified files
      run: |
        echo "DEBUG: Modified files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}

    - name: Determine modified mods
      id: modified_mods
      if: steps.check_commit.outputs.is_release == 'true' || contains(github.event.head_commit.modified, '.github/game_version.json')
      run: |
        $data = Get-Content -Path .github/game_version.json -Raw | ConvertFrom-Json
        $modList = $data.mod_list
        echo "DEBUG: Mod list: [$($modList -join ',')]"
        
        $isAll = $env:GITHUB_OUTPUT -like "*is_all=true*"
        $isGameVersionModified = $env:GITHUB_EVENT_HEAD_COMMIT_MODIFIED -match '\.github/game_version\.json'
        
        echo "DEBUG: Проверяем, есть ли ключевые слова release all ($isAll) или изменён game_version.json ($isGameVersionModified)"
        
        if ($isAll -or $isGameVersionModified) {
          echo "DEBUG: Building all mods because 'release all' keyword was found or game_version.json was modified."
          $updatedMods = $modList -join ','
          echo "DEBUG: UPDATED_MODS=$updatedMods"
          echo "UPDATED_MODS=$updatedMods" >> $env:GITHUB_ENV
        } else {
          $modifiedFiles = git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          echo "DEBUG: Modified files: $modifiedFiles"
          $updatedMods = @()
          foreach ($mod in $modList) {
            if ($modifiedFiles -match "$mod/source/") {
              echo "DEBUG: Modified mod: $mod"
              $updatedMods += $mod
            }
          }
        
          if ($updatedMods.Count -gt 0) {
            echo "DEBUG: Updated mods: $($updatedMods -join ',')"
            echo "UPDATED_MODS=$($updatedMods -join ',')" >> $env:GITHUB_ENV
          } else {
            echo "DEBUG: No mods were updated."
            echo "UPDATED_MODS=" >> $env:GITHUB_ENV
          }
        }

    - name: Debug updated_mods
      run: |
        echo "DEBUG: Updated mods: $updatedMods"
        echo "DEBUG: updated_mods: ${{ steps.versions.outputs.updated_mods }}"

    - name: Pause to ensure environment variable is set 2
      run: sleep 10

    - name: Read game versions and mod versions
      id: versions
      if: env.UPDATED_MODS != ''
      run: |
        $data = Get-Content -Path .github/game_version.json -Raw | ConvertFrom-Json
        $wg_version = $data.CLIENT_VERSION_WG
        $lesta_version = $data.CLIENT_VERSION_RU
    
        $updatedMods = $env:UPDATED_MODS -split ","
        $modVersions = @{}
        foreach ($mod in $updatedMods) {
          $modVersion = Get-Content -Path "$mod/source/VERSION" -Raw | ConvertFrom-Json | Select-Object -ExpandProperty version
          $modVersions[$mod] = $modVersion
        }
    
        $currentDate = Get-Date -Format "yyyy-MM-dd"
        $mark = if ($wg_version) { "World of Tanks" } else { "Tanki Lesta" }
        
        echo "wg_version=$wg_version" >> $env:GITHUB_OUTPUT
        echo "lesta_version=$lesta_version" >> $env:GITHUB_OUTPUT
        echo "updated_mods=$($updatedMods -join ',')" >> $env:GITHUB_OUTPUT
        echo "mod_versions=$($modVersions | ConvertTo-Json -Compress)" >> $env:GITHUB_OUTPUT
        echo "date=$currentDate" >> $env:GITHUB_OUTPUT
        echo "mark=$mark" >> $env:GITHUB_OUTPUT
        echo "client=$wg_version$lesta_version" >> $env:GITHUB_OUTPUT

    - name: Pause to ensure environment variable is set 3
      run: sleep 10

    - name: Run build script
      if: env.UPDATED_MODS != ''
      run: |
        python .github/createRelease.py $env:lesta_version $env:wg_version $env:UPDATED_MODS

    - name: Pause to ensure environment variable is set 4
      run: sleep 10

    - name: Create Release
      id: create_release
      if: steps.modified_mods.outputs.updated_mods != ''
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          ${{ toJson(fromJson(steps.versions.outputs.mod_versions)) }}
        draft: false
        prerelease: false

    - name: Pause to ensure environment variable is set 5
      run: sleep 10

    - name: Upload WG Mod Archives
      if: env.UPDATED_MODS != ''
      run: |
        $updatedMods = "$env:UPDATED_MODS" -split ","
        foreach ($mod in $updatedMods) {
          $archivePath = "$mod/zip/$mod.zip"
          if (Test-Path $archivePath) {
            echo "DEBUG: Uploading $archivePath"
            gh release upload v${{ github.run_number }} $archivePath --clobber
          } else {
            echo "DEBUG: Archive not found: $archivePath"
          }
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Lesta Mod Archives
      if: env.UPDATED_MODS != ''
      run: |
        $updatedMods = "$env:UPDATED_MODS" -split ","
        foreach ($mod in $updatedMods) {
          $archivePath = "$mod/zip/${mod}_RU.zip"
          if (Test-Path $archivePath) {
            echo "DEBUG: Uploading $archivePath"
            gh release upload v${{ github.run_number }} $archivePath --clobber
          } else {
            echo "DEBUG: Archive not found: $archivePath"
          }
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update README files
      if: steps.modified_mods.outputs.updated_mods != ''
      run: |
        $updatedMods = "$UPDATED_MODS" -split ","
        foreach ($mod in $updatedMods) {
          $wgArchiveUrl = "https://github.com/spoter/spoter-mods/releases/download/v${{ github.run_number }}/$mod.zip"
          $lestaArchiveUrl = "https://github.com/spoter/spoter-mods/releases/download/v${{ github.run_number }}/${mod}_RU.zip"
    
          $modVersion = (Get-Content -Path "$mod/source/VERSION" -Raw | ConvertFrom-Json).version
    
          $zipReadmePath = "$mod/zip/README.md"
          $zipReadmeContent = "# $mod\n\n#### Скачать [$mod]: #$modVersion (${{ steps.versions.outputs.date }}) #World of Tanks ${{ steps.versions.outputs.wg_version }}]($wgArchiveUrl)\n\n#### Скачать [$mod]: #$modVersion (${{ steps.versions.outputs.date }}) #Tanki Lesta ${{ steps.versions.outputs.lesta_version }}]($lestaArchiveUrl)"
          Set-Content -Path $zipReadmePath -Value $zipReadmeContent
    
          $modReadmePath = "$mod/README.md"
          $modReadmeContent = "# $mod\n\n#### Скачать [$mod]: #$modVersion (${{ steps.versions.outputs.date }}) #World of Tanks ${{ steps.versions.outputs.wg_version }}]($wgArchiveUrl)\n\n#### Скачать [$mod]: #$modVersion (${{ steps.versions.outputs.date }}) #Tanki Lesta ${{ steps.versions.outputs.lesta_version }}]($lestaArchiveUrl)"
          Set-Content -Path $modReadmePath -Value $modReadmeContent
        }

    - name: Commit and push changes
      if: steps.modified_mods.outputs.updated_mods != ''
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "#update resources for ${{ steps.check_commit.outputs.commit_message }}"
        git push
