name: Python package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '2.7.18' 
        version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python ./.github/createRelease.py
