name: Build and Release

on:
  push:
    branches:
      - master  # Workflow запускается при пуше в ветку master

jobs:
  build:
    runs-on: windows-latest  # Используем Windows для сборки

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50  # Загружаем последние 50 коммитов

      # Шаг 2: Получение информации о пуше
      - name: Get push details
        id: push-details
        shell: pwsh
        run: |
          # Получаем хэш последнего коммита
          $commitHash = git rev-parse HEAD
          Write-Host "✅ Commit hash: $commitHash"

          # Получаем описание пуша (сообщение коммита)
          $commitMessage = git log -1 --pretty=%B
          Write-Host "✅ Commit message: $commitMessage"

          # Экранируем спецсимволы в сообщении коммита
          $escapedCommitMessage = $commitMessage -replace '"', '`"' -replace "'", "''" -replace "`n", " " -replace "`r", " "
          Write-Host "✅ Escaped commit message: $escapedCommitMessage"

          # Получаем список измененных файлов
          $changedFiles = git diff --name-only HEAD^ HEAD
          Write-Host "✅ Changed files:"
          $changedFiles | ForEach-Object { Write-Host "  $_" }

          # Сохраняем данные в выходные переменные
          echo "commit_hash=$commitHash" >> $env:GITHUB_OUTPUT
          echo "commit_message=$escapedCommitMessage" >> $env:GITHUB_OUTPUT
          echo "changed_files=$($changedFiles -join ';')" >> $env:GITHUB_OUTPUT

      # Шаг 3: Установка Python 2.7 через Chocolatey
      - name: Install Python 2.7
        id: install-python
        shell: pwsh
        run: |
          # Проверяем, установлен ли Python 2.7
          if (Test-Path "C:\Python27\python.exe") {
              Write-Host "✅ Python 2.7 is already installed."
              & "C:\Python27\python.exe" --version
              exit 0
          }

          # Проверяем, установлен ли Chocolatey
          if (Get-Command choco -ErrorAction SilentlyContinue) {
              Write-Host "✅ Chocolatey is already installed."
          } else {
              Write-Host "❌ Chocolatey is not installed. Installing now..."
              Set-ExecutionPolicy Bypass -Scope Process -Force
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
              Write-Host "✅ Chocolatey installed successfully."
          }

          # Устанавливаем Python 2.7
          Write-Host "🚀 Installing Python 2.7..."
          choco install python2 -y --force
          Write-Host "✅ Python 2.7 installed successfully."

          # Обновляем переменные окружения
          Write-Host "🔄 Refreshing environment variables..."
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          Write-Host "✅ Environment variables refreshed."

          # Проверяем, что Python 2.7 установился и доступен
          Write-Host "🔍 Checking Python 2.7 installation..."
          & "C:\Python27\python.exe" --version
          if ($LASTEXITCODE -eq 0) {
              Write-Host "✅ Python 2.7 is available in PATH."
          } else {
              Write-Host "❌ Python 2.7 is not available in PATH. Please check the installation."
              exit 1
          }

          # Логируем PATH для отладки
          Write-Host "📂 Current PATH:"
          $env:PATH -split ";" | ForEach-Object { Write-Host "  $_" }

      # Шаг 4: Дебаг и тестирование
      - name: Debug and test
        id: debug-test
        shell: pwsh
        run: |
          # Выводим данные из предыдущих шагов
          Write-Host "🚀 Debug information:"
          Write-Host "Commit hash: ${{ steps.push-details.outputs.commit_hash }}"
          Write-Host "Commit message: ${{ steps.push-details.outputs.commit_message }}"
          Write-Host "Changed files: ${{ steps.push-details.outputs.changed_files }}"

          # Пример использования переменных в PowerShell
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          Write-Host "✅ Escaped commit message in PowerShell: $commitMessage"

          # Пример использования переменных в Python
          & "C:\Python27\python.exe" -c "import sys; print('✅ Escaped commit message in Python: ' + sys.argv[1])" "$commitMessage"