name: Build and Release

on:
  push:
    branches:
      - master # Workflow запускается при пуше в ветку master

jobs:
  build:
    runs-on: windows-latest # Используем Windows для сборки

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50 # Загружаем последние 50 коммитов

      # Шаг 2: Получение информации о пуше
      - name: Get push details
        id: push-details
        shell: pwsh
        run: |
          # Получаем хэш последнего коммита
          $commitHash = git rev-parse HEAD
          Write-Host "✅ Commit hash: $commitHash"

          # Получаем описание пуша (сообщение коммита)
          $commitMessage = git log -1 --pretty=%B
          Write-Host "✅ Commit message: $commitMessage"

          # Экранируем спецсимволы в сообщении коммита
          $escapedCommitMessage = $commitMessage -replace '"', '`"' -replace "'", "''" -replace "`n", " " -replace "`r", " "
          Write-Host "✅ Escaped commit message: $escapedCommitMessage"

          # Получаем список изменённых файлов
          $changedFiles = git diff --name-only HEAD^ HEAD
          Write-Host "✅ Changed files:"
          $changedFiles | ForEach-Object { Write-Host " $_" }

          # Сохраняем данные в выходные переменные
          echo "commit_hash=$commitHash" >> $env:GITHUB_OUTPUT
          echo "commit_message=$escapedCommitMessage" >> $env:GITHUB_OUTPUT
          echo "changed_files=$($changedFiles -join ';')" >> $env:GITHUB_OUTPUT

      # Шаг 3: Установка Python 2.7
      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7' # Явно указываем версию Python

      # Шаг 4: Проверка сообщения коммита на ключевые слова
      - name: Check commit message for release keywords
        id: check_commit
        shell: pwsh
        run: |
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          if ($commitMessage -match 'release') {
            Write-Host "Is release: true"
            echo "is_release=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "Is release: false"
            echo "is_release=false" >> $env:GITHUB_OUTPUT
          }
          if ($commitMessage -match 'all') {
            Write-Host "Is all: true"
            echo "is_all=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "Is all: false"
            echo "is_all=false" >> $env:GITHUB_OUTPUT
          }

      # Шаг 5: Дебаг и тестирование
      - name: Debug and test
        id: debug-test
        shell: pwsh
        run: |
          # Выводим данные из предыдущих шагов
          Write-Host "🚀 Debug information:"
          Write-Host "Commit hash: ${{ steps.push-details.outputs.commit_hash }}"
          Write-Host "Commit message: ${{ steps.push-details.outputs.commit_message }}"
          Write-Host "Changed files: ${{ steps.push-details.outputs.changed_files }}"
          Write-Host "Is release: ${{ steps.check_commit.outputs.is_release }}"
          Write-Host "Is all: ${{ steps.check_commit.outputs.is_all }}"

          # Пример использования переменных в PowerShell
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          Write-Host "✅ Escaped commit message in PowerShell: $commitMessage"

          # Устанавливаем кодировку UTF-8 для Python
          $env:PYTHONIOENCODING = "utf-8"
          Write-Host "✅ Set PYTHONIOENCODING to utf-8."

          # Проверяем кодировку в Python
          & "C:\Python27\python.exe" -c "import sys; print('Python default encoding: ' + sys.getdefaultencoding())"
          & "C:\Python27\python.exe" -c "import sys; print('Python stdout encoding: ' + sys.stdout.encoding)"
          & "C:\Python27\python.exe" -c "import sys; print('Python file system encoding: ' + sys.getfilesystemencoding())"

      # Шаг 6: Углублённый дебаг и тестирование переменных
      - name: Deep debug and test variables
        shell: pwsh
        run: |
          Write-Host "Deep debugging variables:"
          Write-Host "Commit hash: ${{ steps.push-details.outputs.commit_hash }}"
          Write-Host "Commit message: ${{ steps.push-details.outputs.commit_message }}"
          Write-Host "Changed files: ${{ steps.push-details.outputs.changed_files }}"
          Write-Host "Is release: ${{ steps.check_commit.outputs.is_release }}"
          Write-Host "Is all: ${{ steps.check_commit.outputs.is_all }}"