name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

        # Проверка на наличие ошибок после checkout
        run: |
          git gc --force
          if ($LASTEXITCODE -ne 0) {
            Write-Host "❌ Error: Failed to clone repository."
            exit 1
          }

      - name: Get push details
        id: push-details
        shell: pwsh
        run: |
          $commitHash = git rev-parse HEAD
          Write-Host "✅ Commit hash: $commitHash"

          $commitMessage = git log -1 --pretty=%B
          Write-Host "✅ Commit message: $commitMessage"

          # Экранирование специальных символов
          $escapedCommitMessage = $commitMessage -replace '"', '`"' -replace "'", "''" -replace "`n", " " -replace "`r", " "
          Write-Host "✅ Escaped commit message: $escapedCommitMessage"

          # Получение списка измененных файлов
          $changedFiles = git diff --name-only HEAD^ HEAD
          Write-Host "✅ Changed files:"
          $changedFiles | ForEach-Object { Write-Host "  $_" }

          # Сохранение данных в переменные окружения
          echo "commit_hash=$commitHash" >> $env:GITHUB_OUTPUT
          echo "commit_message=$escapedCommitMessage" >> $env:GITHUB_OUTPUT
          echo "changed_files=$($changedFiles -join ';')" >> $env:GITHUB_OUTPUT

      - name: Install Python 2.7
        id: install-python
        shell: pwsh
        run: |
          # Проверка на наличие Python 2.7 в PATH
          if (Test-Path "C:\Python27\python.exe") {
            Write-Host "✅ Python 2.7 is already installed."
            & "C:\Python27\python.exe" --version
            exit 0
          }

          # Проверка на наличие Chocolatey
          if (Get-Command choco -ErrorAction SilentlyContinue) {
            Write-Host "✅ Chocolatey is already installed."
          } else {
            Write-Host "❌ Chocolatey is not installed. Installing now..."
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
            Write-Host "✅ Chocolatey installed successfully."
          }

          # Установка Python 2.7
          Write-Host "🚀 Installing Python 2.7..."
          choco install python2 -y --force
          Write-Host "✅ Python 2.7 installed successfully."

          # Обновление окружения
          Write-Host "🔄 Refreshing environment variables..."
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          Write-Host "✅ Environment variables refreshed."

          # Проверка установки Python 2.7
          Write-Host "🔍 Checking Python 2.7 installation..."
          & "C:\Python27\python.exe" --version
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Python 2.7 is available in PATH."
          } else {
            Write-Host "❌ Python 2.7 is not available in PATH. Please check the installation."
            exit 1
          }

          # Логирование PATH
          Write-Host "📂 Current PATH:"
          $env:PATH -split ";" | ForEach-Object { Write-Host "  $_" }

      - name: Check commit message for release keywords
        id: check_commit
        shell: pwsh
        run: |
          # Получение переменных из предыдущего шага
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          $changedFiles = "${{ steps.push-details.outputs.changed_files }}" -split ";"

          Write-Host "🔍 Checking commit message for release keywords..."

          # Проверка на наличие ключевых слов
          $releasePattern = "(?i)release|релиз"
          $allPattern = "(?i)all|всех|все|всё"

          $isRelease = $commitMessage -match $releasePattern
          $isAll = $commitMessage -match $allPattern

          # Проверка изменения файла .github/game_version.json
          $isGameVersionChanged = $changedFiles -contains ".github/game_version.json"

          # Логирование результатов проверки
          if ($isRelease) {
            Write-Host "✅ Commit message contains release keyword."
            echo "is_release=true" >> $env:GITHUB_OUTPUT

            if ($isAll -or $isGameVersionChanged) {
              Write-Host "✅ is_all=true"
              echo "is_all=true" >> $env:GITHUB_OUTPUT
            } else {
              Write-Host "✅ is_all=false"
              echo "is_all=false" >> $env:GITHUB_OUTPUT
            }
          } else {
            Write-Host "❌ Commit message does not contain release keyword. Skipping build."
            echo "is_release=false" >> $env:GITHUB_OUTPUT
            echo "is_all=false" >> $env:GITHUB_OUTPUT
          }

      - name: Debug and Test
        id: debug-test
        shell: pwsh
        run: |
          Write-Host "🚀 Debug information:"
          Write-Host "✅ Commit hash: ${{ steps.push-details.outputs.commit_hash }}"
          Write-Host "✅ Commit message: ${{ steps.push-details.outputs.commit_message }}"

          # Пример работы с переменными в PowerShell
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          Write-Host "✅ Escaped commit message in PowerShell: $commitMessage"

          # Пример работы с переменными в Python 2.7
          & "C:\Python27\python.exe" -c "import sys; print('✅ Escaped commit message in Python: ' + sys.argv[1].encode('utf-8').decode('utf-8'))" "$commitMessage"

          # Дополнительные проверки
          Write-Host "🔄 Environment variables after refresh:"
          $env:PATH -split ";" | ForEach-Object { Write-Host "  $_" }
