name: Build and Release

on:
  push:
    branches:
      - master # Workflow запускается при пуше в ветку master

jobs:
  build:
    runs-on: windows-latest # Используем Windows для сборки

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50 # Загружаем последние 50 коммитов

      # Шаг 2: Получение информации о пуше
      - name: Get push details
        id: push-details
        shell: pwsh
        run: |
          # Получаем хэш последнего коммита
          $commitHash = git rev-parse HEAD
          Write-Host "✅ Commit hash: $commitHash"

          # Получаем описание пуша (сообщение коммита)
          $commitMessage = git log -1 --pretty=%B
          Write-Host "✅ Commit message: $commitMessage"

          # Экранируем спецсимволы в сообщении коммита
          $escapedCommitMessage = $commitMessage -replace '"', '`"' -replace "'", "''" -replace "`n", " " -replace "`r", " "
          Write-Host "✅ Escaped commit message: $escapedCommitMessage"

          # Получаем список измененных файлов
          $changedFiles = git diff --name-only HEAD^ HEAD
          Write-Host "✅ Changed files:"
          $changedFiles | ForEach-Object { Write-Host "  $_" }

          # Сохраняем данные в выходные переменные
          echo "commit_hash=$commitHash" >> $env:GITHUB_OUTPUT
          echo "commit_message=$escapedCommitMessage" >> $env:GITHUB_OUTPUT
          echo "changed_files=$($changedFiles -join ';')" >> $env:GITHUB_OUTPUT

      # Шаг 3: Установка Python 2.7 через Chocolatey
      - name: Install Python 2.7
        id: install-python
        shell: pwsh
        run: |
          # Проверяем, установлен ли Python 2.7
          if (Test-Path "C:\Python27\python.exe") {
              Write-Host "✅ Python 2.7 is already installed."
              & "C:\Python27\python.exe" --version
              exit 0
          }

          # Проверяем, установлен ли Chocolatey
          if (Get-Command choco -ErrorAction SilentlyContinue) {
              Write-Host "✅ Chocolatey is already installed."
          } else {
              Write-Host "❌ Chocolatey is not installed. Installing now..."
              Set-ExecutionPolicy Bypass -Scope Process -Force
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              try {
                  iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
                  Write-Host "✅ Chocolatey installed successfully."
              } catch {
                  Write-Host "❌ Error installing Chocolatey: $_"
                  exit 1
              }
          }

          # Устанавливаем Python 2.7
          Write-Host "🚀 Installing Python 2.7..."
          try {
              choco install python2 -y --force
              Write-Host "✅ Python 2.7 installed successfully."
          } catch {
              Write-Host "❌ Error installing Python 2.7: $_"
              exit 1
          }

          # Обновляем переменные окружения
          Write-Host "🔄 Refreshing environment variables..."
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          Write-Host "✅ Environment variables refreshed."

          # Проверяем, что Python 2.7 установился и доступен
          Write-Host "🔍 Checking Python 2.7 installation..."
          & "C:\Python27\python.exe" --version
          if ($LASTEXITCODE -eq 0) {
              Write-Host "✅ Python 2.7 is available in PATH."
          } else {
              Write-Host "❌ Python 2.7 is not available in PATH. Please check the installation."
              exit 1
          }

          # Логируем PATH для отладки
          Write-Host "📂 Current PATH:"
          $env:PATH -split ";" | ForEach-Object { Write-Host "  $_" }

      # Шаг 4: Проверка сообщения коммита на ключевые слова
      - name: Check commit message for release keywords
        id: check_commit
        shell: pwsh
        run: |
          # Получаем сообщение коммита
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          Write-Host "🔍 Checking commit message for release keywords..."

          # Получаем список измененных файлов
          $changedFiles = "${{ steps.push-details.outputs.changed_files }}" -split ";"
          Write-Host "✅ Changed files: $changedFiles"

          # Определяем шаблоны для поиска ключевых слов
          $releasePattern = "(?i)release|релиз"
          $allPattern = "(?i)all|всех|все|всё"

          # Проверяем, содержит ли сообщение коммита ключевые слова
          $isRelease = $commitMessage -match $releasePattern
          $isAll = $commitMessage -match $allPattern

          # Проверяем, изменен ли файл .github/game_version.json
          $isGameVersionChanged = $changedFiles -contains ".github/game_version.json"

          # Логируем результаты проверки
          if ($isRelease) {
              Write-Host "✅ Commit message contains release keyword."
              Write-Host "✅ commit_message=$commitMessage"
              Write-Host "✅ is_release=true"
              echo "commit_message=$commitMessage" >> $env:GITHUB_OUTPUT
              echo "is_release=true" >> $env:GITHUB_OUTPUT

              if ($isAll -or $isGameVersionChanged) {
                  Write-Host "✅ is_all=true"
                  echo "is_all=true" >> $env:GITHUB_OUTPUT
              } else {
                  Write-Host "✅ is_all=false"
                  echo "is_all=false" >> $env:GITHUB_OUTPUT
              }
          } else {
              Write-Host "❌ Commit message does not contain release keyword. Skipping build."
              Write-Host "❌ is_release=false"
              echo "is_release=false" >> $env:GITHUB_OUTPUT
              Write-Host "❌ is_all=false"
              echo "is_all=false" >> $env:GITHUB_OUTPUT
          }

      # Шаг 5: Дебаг и тестирование
      - name: Debug and test
        id: debug-test
        shell: pwsh
        run: |
          # Выводим данные из предыдущих шагов
          Write-Host "🚀 Debug information:"
          Write-Host "Commit hash: ${{ steps.push-details.outputs.commit_hash }}"
          Write-Host "Commit message: ${{ steps.push-details.outputs.commit_message }}"
          Write-Host "Changed files: ${{ steps.push-details.outputs.changed_files }}"
          Write-Host "Is release: ${{ steps.check_commit.outputs.is_release }}"
          Write-Host "Is all: ${{ steps.check_commit.outputs.is_all }}"
      
          # Пример использования переменных в PowerShell
          $commitMessage = "${{ steps.push-details.outputs.commit_message }}"
          Write-Host "✅ Escaped commit message in PowerShell: $commitMessage"
      
          # Устанавливаем кодировку UTF-8 для Python
          $env:PYTHONIOENCODING = "utf-8"
          Write-Host "✅ Set PYTHONIOENCODING to utf-8."
      
          # Проверяем кодировку в Python
          & "C:\Python27\python.exe" -c "import sys; print('Python default encoding: ' + sys.getdefaultencoding())"
          & "C:\Python27\python.exe" -c "import sys; print('Python stdout encoding: ' + sys.stdout.encoding)"
          & "C:\Python27\python.exe" -c "import sys; print('Python file system encoding: ' + sys.getfilesystemencoding())"
      
          # Изменяем кодовую страницу консоли на UTF-8
          chcp 65001
      
          # Выводим сообщение с использованием UTF-8
          & "C:\Python27\python.exe" -c "import sys; print('✅ Escaped commit message in Python: ' + sys.argv[1].decode('utf-8'))" "$commitMessage"

      # Шаг 6: Углублённый дебаг и тестирование переменных
      - name: Deep debug and test variables
        id: deep-debug
        shell: pwsh
        run: |
          # Выводим все переменные из предыдущих шагов
          Write-Host "🚀 Deep debug information:"
          Write-Host "Commit hash: ${{ steps.push-details.outputs.commit_hash }}"
          Write-Host "Commit message: ${{ steps.push-details.outputs.commit_message }}"
          Write-Host "Changed files: ${{ steps.push-details.outputs.changed_files }}"
          Write-Host "Is release: ${{ steps.check_commit.outputs.is_release }}"
          Write-Host "Is all: ${{ steps.check_commit.outputs.is_all }}"
      
          # Проверяем, что все переменные корректно переданы
          $errors = @()
          if (-not "${{ steps.push-details.outputs.commit_hash }}") {
              $errors += "Commit hash is empty!"
          }
          if (-not "${{ steps.push-details.outputs.commit_message }}") {
              $errors += "Commit message is empty!"
          }
          if (-not "${{ steps.push-details.outputs.changed_files }}") {
              $errors += "Changed files list is empty!"
          }
          if (-not "${{ steps.check_commit.outputs.is_release }}") {
              $errors += "Is release flag is empty!"
          }
          if (-not "${{ steps.check_commit.outputs.is_all }}") {
              $errors += "Is all flag is empty!"
          }
      
          if ($errors.Count -gt 0) {
              Write-Host "❌ Errors found:"
              $errors | ForEach-Object { Write-Host " - $_" }
              exit 1
          } else {
              Write-Host "✅ All variables are correctly set and passed."
          }