name: 🧹 Очистка запусков 🧹

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Режим тестирования (true=логи, false=удаление)'
        required: false
        default: 'true'
      keep_last:
        description: 'Минимальное количество сохраняемых запусков'
        required: false
        default: '3'
      max_days:
        description: 'Удалять старше X дней (0=отключить)'
        required: false
        default: '7'
      exclude_branches:
        description: 'Ветки для исключения (через запятую)'
        required: false

  schedule:
    - cron: "0 4 * * *" # 07:00 МСК

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      LIMIT: 100

    steps:
      # ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
      # 🛠️ ИНИЦИАЛИЗАЦИЯ
      # ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
      - name: Инициализация параметров
        run: |
          echo "▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜"
          echo "▌ Запуск: $(date +'%Y-%m-%d %H:%M') МСК"
          echo "▌ Репозиторий: ${{ github.repository }}"
          echo "▌ Параметры:"
          echo "▌ • Тестовый режим: ${{ inputs.dry_run }}"
          echo "▌ • Сохранить последних: ${{ inputs.keep_last }}"
          echo "▌ • Удалить старше: ${{ inputs.max_days }} дней"
          echo "▌ • Исключённые ветки: ${{ inputs.exclude_branches }}"
          echo "▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟"

      # ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
      # 🗑️ ОСНОВНАЯ ЛОГИКА
      # ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
      - name: Анализ и удаление
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Рассчёт граничной даты
          if [ "${{ inputs.max_days }}" = "0" ]; then
           cutoff_date="1970-01-01T00:00:00Z"
          else
           cutoff_date=$(date -d "${{ inputs.max_days }} days ago" +"%Y-%m-%dT%H:%M:%SZ")
          fi

          # Получение всех workflow
          gh api repos/${{ github.repository }}/actions/workflows | jq -r '.workflows[] | "\(.id)|\(.name)"' | while IFS='|' read -r wf_id wf_name; do
            
            echo "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀"
            echo " Обработка: $wf_name"
            echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░"

            # Фильтрация запусков
            runs=$(gh api "repos/${{ github.repository }}/actions/workflows/$wf_id/runs?per_page=$LIMIT" | jq -r \
             --arg cutoff "$cutoff_date" \
             --arg exclude "${{ inputs.exclude_branches }}" \
             '.workflow_runs[] | select(
               .status != "in_progress" and 
               (.created_at < $cutoff or $cutoff == "1970-01-01T00:00:00Z") and 
               (($exclude == "") or (.branch | inside($exclude | split(",") | map(trim)) | not))
             ) | "\(.id)|\(.status)|\(.created_at)|\(.branch)|\(.head_commit.message)"')
            # Сортировка и выборка
            sorted_runs=$(echo "$runs" | sort -t'|' -k3 -r)
            to_delete=$(echo "$sorted_runs" | tail -n +$((${{ inputs.keep_last }} + 1)))

            if [ -n "$to_delete" ]; then
              echo "╞════════════════════════════════"
              echo " 📊 Статистика:"
              echo " ├ Всего запусков: $(echo "$sorted_runs" | wc -l)"
              echo " ├ Сохраняем: ${{ inputs.keep_last }}"
              echo " └ Удаляем: $(echo "$to_delete" | wc -l)"
              echo "╘════════════════════════════════"

              echo "$to_delete" | while IFS='|' read -r run_id status created_at branch commit_msg; do
                human_date=$(date -d "$created_at" +"%Y-%m-%d %H:%M")
                echo " ┌ ID: $run_id"
                echo " ├ Статус: $status"
                echo " ├ Ветка: ${branch:-main}"
                echo " ├ Дата: $human_date"
                echo " └ Коммит: ${commit_msg:0:50}..."
                
                # Реальное удаление
                if [ "${{ inputs.dry_run }}" = "false" ]; then
                  gh api -X DELETE "repos/${{ github.repository }}/actions/runs/$run_id"
                fi
              done
            else
              echo "╞════════════════════════════════"
              echo " ✅ Нет запусков для удаления"
              echo "╘════════════════════════════════"
            fi
            echo "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
          done

      # ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
      # 📅 ИТОГИ
      # ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
      - name: Финальный отчёт
        if: always()
        run: |
          echo "▛▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▜"
          echo "▌ Завершено: $(date +'%Y-%m-%d %H:%M') МСК"
          echo "▌ Отчёт: https://github.com/${{ github.repository }}/actions"
          echo "▙▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▟"
