name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: "0 0 * * *" # Ежедневно в 00:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup workflow runs
        uses: c-hive/gha-remove-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-and-release.yml  # Имя вашего workflow-файла
          keep: 3        # Оставить последние 3 запуска
          keep_days: 0   # Не сохранять запуски по времени
