name: 🧹 Cleanup Workflow Runs

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Только логирование (true/false)'
        required: false
        default: 'false'
      target_statuses:
        description: 'Статусы через запятую (completed, failure и др.)'
        required: false
        default: 'completed,failure,cancelled'
      exclude_workflows:
        description: 'Исключить workflow по названиям'
        required: false

  schedule:
    - cron: "0 4 * * *" # 07:00 МСК

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      KEEP_LAST: 3
      LIMIT_PER_WORKFLOW: 100

    steps:
      - name: 🔧 Инициализация
        run: |
          echo "🔄 Запуск: $(date +'%d.%m.%Y %H:%M')"
          echo "Репозиторий: ${{ github.repository }}"
          echo "Параметры:"
          echo "- Тестовый режим: ${{ inputs.dry_run }}"
          echo "- Удаляемые статусы: ${{ inputs.target_statuses }}"
          echo "- Исключения: ${{ inputs.exclude_workflows }}"

      - name: 🗑️ Очистка запусков
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Получение списка всех workflow
          workflows=$(gh api repos/${{ github.repository }}/actions/workflows | jq -r '.workflows[] | "\(.id)|\(.name)"')

          echo "$workflows" | while IFS='|' read -r wf_id wf_name; do
            # Проверка исключений
            if [[ "${{ inputs.exclude_workflows }}" == *"$wf_name"* ]]; then
              echo "⏭️ Пропуск: $wf_name"
              continue
            fi

            echo "🔍 Обработка: $wf_name (ID: $wf_id)"
            
            # Получение запусков с фильтрацией
            runs=$(gh api "repos/${{ github.repository }}/actions/workflows/$wf_id/runs?per_page=$LIMIT_PER_WORKFLOW&status=completed" | 
              jq -r --arg statuses "${{ inputs.target_statuses }}" \
              '.workflow_runs[] | select(.status as $s | $s == ($ARGS.named.statuses | split(",")[])) | "\(.id)|\(.status)|\(.created_at)"')

            # Сортировка и фильтрация
            to_delete=$(echo "$runs" | sort -t'|' -k3 -r | tail -n +$(($KEEP_LAST + 1)))

            # Логирование
            echo "📊 Статистика:"
            echo "Всего запусков: $(echo "$runs" | wc -l)"
            echo "Сохраняем: $KEEP_LAST"
            echo "Удаляем: $(echo "$to_delete" | wc -l)"

            # Удаление
            if [ -n "$to_delete" ]; then
              echo "$to_delete" | while IFS='|' read -r run_id status date; do
                echo "🚮 Удаление: ID $run_id (статус: $status, дата: $date)"
                if [ "${{ inputs.dry_run }}" = "false" ]; then
                  gh api -X DELETE "repos/${{ github.repository }}/actions/runs/$run_id"
                fi
              done
            fi
            echo "────────────────────"
          done

      - name: 📈 Итоги
        if: always()
        run: |
          echo "✅ Завершено: $(date +'%H:%M:%S')"
          echo "Ссылка: https://github.com/${{ github.repository }}/actions"
